version: "3.8"

services:
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    volumes:
      - .:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  poem-sqlx-service:
    container_name: poem-sqlx-service
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    environment:
      - "DATABASE_URL=${DATABASE_URL?please set}"
      - "LISTEN_ADDRESS=${LISTEN_ADDRESS:-0.0.0.0:8000}"
      - "RUST_BACKTRACE=${BACKTRACE:-1}"
      - "RUST_LOG=${LOG_LEVEL:-debug}"
    tty: true
