version: "3.8"

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD?please set}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-db}"
    volumes:
      - ./db/mysql-data:/data
      - ./data/init:/docker-entrypoint-initdb.d
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD?please set}"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
  main-service:
    container_name: main-service
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_URL=${POSTGRES_URL?please set}"
      - "MYSQL_URL=${MYSQL_URL?please set}"
      - "LISTEN_ADDRESS=${LISTEN_ADDRESS:-0.0.0.0:8000}"
      - "RUST_BACKTRACE=${BACKTRACE:-1}"
      - "RUST_LOG=${LOG_LEVEL:-debug}"
      - "API_URL=${API_URL:-http://localhost:8000/api}"
